In [1]:
#Importando a biblioteca NLTK
import nltk
nltk.download()

NLTK Downloader
---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader> d

Download which package (l=list; x=cancel)?
  Identifier> all
       | 
       | Downloading package abc to /root/nltk_data...
       |   Unzipping corpora/abc.zip.
       | Downloading package alpino to /root/nltk_data...
       |   Unzipping corpora/alpino.zip.
       | Downloading package biocreative_ppi to /root/nltk_data...
       |   Unzipping corpora/biocreative_ppi.zip.
       | Downloading package brown to /root/nltk_data...
       |   Unzipping corpora/brown.zip.
       | Downloading package brown_tei to /root/nltk_data...
       |   Unzipping corpora/brown_tei.zip.
       | Downloading package cess_cat to /root/nltk_data...
       |   Unzipping corpora/cess_cat.zip.
       | Downloading package cess_esp to /root/nltk_data...
 

True

In [3]:
#Importando o pandas
import pandas as pd
base = pd.read_excel('Base - Título de Notícias.xlsx')
print(base.columns)
base.head()

Index(['Notícia', 'Sentimento'], dtype='object')


Notícia Sentimento
0  diretor petrobras nega organização criminosa e...   positivo
1  tom cauteloso janet yellen pressiona bolsas fo...     neutro
2  bovespa caminha nova máxima ano quarta alta se...   positivo
3  após abrir estável ibovespa passa registrar qu...   negativo
4  paulo miranda reivindica iluminação telefonia ...   positivo

In [4]:
#Checando se possui algum valor mulo
base.isnull().sum()

Notícia       0
Sentimento    0
dtype: int64

In [5]:
#Verificando o quantitativo dos indicadores
base['Sentimento'].value_counts()

 positivo    925
 negativo    746
 neutro      452
Name: Sentimento, dtype: int64

In [0]:
#Divisão da base em treino e teste, sendo 30% para teste, e 70% para treinamento
from sklearn.model_selection import train_test_split
preditor = base['Notícia']
classe = base['Sentimento']
preditor_tr, preditor_te, classe_tr, classe_te = train_test_split(preditor, classe, test_size = 0.3, random_state = 0)

In [7]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.neighbors import KNeighborsClassifier
titulo_model = Pipeline([('tfidf', TfidfVectorizer()), ('clf',
                                           KNeighborsClassifier())])
titulo_model.fit(preditor_tr, classe_tr)

Pipeline(memory=None,
         steps=[('tfidf',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words=None, strip_accents=None,
                                 sublinear_tf=False,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, use_idf=True,
                                 vocabulary=None)),
                ('clf',
                 KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                      metric='minkowski', metric_params=None,

In [0]:
predicao_kn = titulo_model.predict(preditor_te)

In [9]:
from sklearn import metrics
print(metrics.confusion_matrix(classe_te, predicao_kn))

[[153  14  57]
 [ 43  38  55]
 [ 42  29 206]]


In [10]:
print(metrics.classification_report(classe_te, predicao_kn))

              precision    recall  f1-score   support

    negativo       0.64      0.68      0.66       224
      neutro       0.47      0.28      0.35       136
    positivo       0.65      0.74      0.69       277

    accuracy                           0.62       637
   macro avg       0.59      0.57      0.57       637
weighted avg       0.61      0.62      0.61       637



In [11]:
print(metrics.accuracy_score(classe_te, predicao_kn))

0.6232339089481946
